/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Basket-field.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Basket-field.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['machine-body'].geometry} material={materials['Material.003']} position={[0.115, 7.498, -20.299]} scale={[5.521, 5.738, 5.521]} />
      <mesh geometry={nodes['machine-hopper'].geometry} material={materials['Material.005']} position={[0.138, 19.711, -22.62]} scale={1.717} />
      <mesh geometry={nodes['tapa-hopper'].geometry} material={nodes['tapa-hopper'].material} position={[0.152, 12.77, -22.62]} scale={[1.319, 0.048, 1.319]} />
      <group position={[0.055, 28.381, -25.714]} rotation={[0, Math.PI / 2, 0]} scale={[0.243, 4.178, 6.323]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.net.geometry} material={nodes.net.material} position={[0.055, 22.576, -22.584]} rotation={[-Math.PI, 0, 0]} scale={-1.601} />
      <mesh geometry={nodes.ring.geometry} material={materials['Material.004']} position={[0.055, 25.673, -22.584]} scale={[1.174, 1, 1.174]} />
      <mesh geometry={nodes['ring-support'].geometry} material={materials['Material.004']} position={[0.055, 25.117, -25.175]} scale={[0.849, 0.616, 0.379]} />
      <mesh geometry={nodes.Floor.geometry} material={materials['Material.002']} position={[0, 0, -5.385]} scale={-163.222} />
      <mesh geometry={nodes['Throw-base'].geometry} material={nodes['Throw-base'].material} position={[0.006, 1.222, 63.593]} scale={[4.971, 1, 12.97]} />
      <mesh geometry={nodes['cannon-base'].geometry} material={nodes['cannon-base'].material} position={[0.006, 7.597, 43.35]} rotation={[0.742, 0, 0]} scale={[4.806, 1, 9.772]} />
      <mesh geometry={nodes['Can-case'].geometry} material={materials['Material.004']} position={[-0.352, 2.996, -0.446]} scale={[7.188, 4.28, 10.752]} />
    </group>
  )
}

useGLTF.preload('/Basket-field.glb')
