/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/box.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/box.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box.geometry} material={materials['Material.006']} position={[0.32, 2.355, 1.784]} scale={[1.74, 2.214, 7.338]} />
      <mesh geometry={nodes['Box-cover'].geometry} material={materials['Material.006']} position={[4.304, 4.802, 1.722]} scale={[1.864, 0.198, 7.459]} />
    </group>
  )
}

useGLTF.preload('/box.glb')
