/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/cans-machine.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cans-machine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['machine-body'].geometry} material={materials['Material.003']} position={[0.11, 7.593, -25.666]} scale={[10.107, 6.427, 10.107]} />
      <mesh geometry={nodes['machine-hopper'].geometry} material={materials['Material.005']} position={[0.143, 21.273, -30.085]} scale={[2.521, 1.94, 2.465]} />
      <mesh geometry={nodes['tapa-hopper'].geometry} material={materials['Material.005']} position={[0.346, 13.224, -28.288]} scale={[2.775, 0.076, 4.667]} />
    </group>
  )
}

useGLTF.preload('/cans-machine.glb')
