/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/number.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/number.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['cube-6'].geometry} material={nodes['cube-6'].material} position={[0, 4.765, 0]} scale={[1, 3.92, 1]} />
      <mesh geometry={nodes['cube-5'].geometry} material={nodes['cube-5'].material} position={[0, 14.478, 0]} scale={[1, 3.92, 1]} />
      <mesh geometry={nodes['cube-0'].geometry} material={nodes['cube-0'].material} position={[10.97, 14.478, 0]} scale={[1, 3.92, 1]} />
      <mesh geometry={nodes['cube-1'].geometry} material={nodes['cube-1'].material} position={[10.97, 4.812, 0]} scale={[1, 3.92, 1]} />
      <mesh geometry={nodes['cube-2'].geometry} material={nodes['cube-2'].material} position={[5.352, 20.286, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 3.92, 1]} />
      <mesh geometry={nodes['cube-4'].geometry} material={nodes['cube-4'].material} position={[5.447, -1.06, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 3.92, 1]} />
      <mesh geometry={nodes['cube-3'].geometry} material={nodes['cube-3'].material} position={[5.529, 9.716, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 3.647, 1]} />
    </group>
  )
}

useGLTF.preload('/number.glb')
