/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/pusher.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pusher.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pusher.geometry} material={materials['Material.012']} position={[20.417, 1.203, 1.922]} scale={[0.377, 1.528, 9.668]} />
    </group>
  )
}

useGLTF.preload('/pusher.glb')
