/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/tomato-cannon.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tomato-cannon.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.006, 4.844, 57.456]} scale={[8.803, 8.803, 14.304]}>
        <mesh geometry={nodes.catapult_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.catapult_2.geometry} material={materials['Material.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tomato-cannon.glb')
