/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/tomato.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tomato.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tomato.geometry} material={materials['Material.002']} position={[-0.334, 1.894, 0]} scale={[1.582, 1.344, 1.344]} />
      <mesh geometry={nodes.leafs.geometry} material={materials['Material.001']} position={[-0.318, 3.02, -0.023]} scale={[0.2, 0.13, 0.2]} />
    </group>
  )
}

useGLTF.preload('/tomato.glb')
