/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/tomato-can.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tomato-can.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.074, 0]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tomato-can.glb')
