/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Basket-field.glb 
*/

import React, { useEffect, useRef, useState } from 'react';
import { Box, useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';
import { useFrame } from '@react-three/fiber';
import { useMoveAndReset } from '../hooks/movement';
import { Vector3 } from 'three';

export function BasketField(props) {
  const { nodes, materials } = useGLTF('/Basket-field.glb');

  return (
    <group {...props} dispose={null} scale={0.5}>
      <RigidBody type='fixed' colliders='cuboid'>
        <mesh
          geometry={nodes.floor.geometry}
          material={materials['Material.011']}
          position={[35.67, -0.36, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[177.077, 1, 177.077]}
        />
      </RigidBody>
      <mesh
        geometry={nodes['Wall-teleport'].geometry}
        material={materials['Material.011']}
        position={[-106.001, 32.432, -3.869]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[115.105, 170.239, 182.458]}
      />
      <mesh
        geometry={nodes['wall-lateral'].geometry}
        material={materials['Material.011']}
        position={[-3.945, 32.544, -176.565]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={[115.105, 170.239, 182.458]}
      />
      <mesh
        geometry={nodes.rail.geometry}
        material={materials['Material.012']}
        position={[-58.083, -1.323, 2.305]}
        scale={[80.772, 0.584, 0.948]}
      />
    </group>
  );
}

useGLTF.preload('/Basket-field.glb');
